# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Intro
    url: /#exp
    weight: 11
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  - name: News
    url: /#news
    weight: 12
  
  - name: Blog
    url: post/
    weight: 13

  - name: Tags
    identifier: tags
    url: tags/
    weight: 14
  - name: Moment
    parent: tags
    url: tags/moment/
    weight: 20
  - name: Campus
    parent: tags
    url: tags/campus/
    weight: 20
  - name: Sport
    parent: tags
    url: tags/sport/
    weight: 20